"""fix StudentTable [adress -> not uniqe]

Revision ID: 7c8b7792baed
Revises: b20406282ce7
Create Date: 2025-03-05 13:11:25.919499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8b7792baed'
down_revision: Union[str, None] = 'b20406282ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_address_key', 'students', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('students_address_key', 'students', ['address'])
    # ### end Alembic commands ###
